server:
  port: 8080

spring:
  application:
    name: account-service
  profiles:
    active: prod
  datasource:
    url: jdbc:mysql://account-database:3306/account?useSSL=false&allowPublicKeyRetrieval=true
    username: "root"
    password: "0000"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
  flyway: # This is for the database migration
    enabled: true
    baseline-version: 1.0.0
    baseline-on-migrate: true
    validate-on-migrate: true
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    default-schema: account
  config:
    import: optional:configserver:http://config:8071
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint: # This is for the /actuator/shutdown endpoint
    shutdown:
      enabled: true
  info: # This is for the /actuator/info endpoint
    env:
      enabled: true

endpoints: # Enable the /actuator/shutdown endpoint
  shutdown:
    enabled: true

eureka:
  instance:
    appname: account
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-server:8070/eureka/

info: # This is for the /actuator/info endpoint to be seen in eureka dashboard
  app:
    name: "account"
    description: "Account Service for Bank Application"
    version: "1.0.0"