spring:
  application:
    name: config
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: "classpath:/config"

encrypt:
  key: 3A2A167DDDC28783744B92EAE8191

server:
  port: 8071
