version: "3.7"
services:
  account:
    image: timlien/account:1.0.0
    container_name: account
    ports:
      - "8080:8080"
    deploy:
        replicas: 1
        resources:
            limits:
              memory: 700M
    networks:
      - spring-cloud-network
  loan:
    image: timlien/loan:1.0.0
    container_name: loan
    ports:
      - "8090:8090"
    deploy:
        replicas: 1
        resources:
            limits:
              memory: 700M
    networks:
      - spring-cloud-network
  card:
    image: timlien/card:1.0.0
    container_name: card
    ports:
      - "9000:9000"
    deploy:
        replicas: 1
        resources:
            limits:
              memory: 700M
    networks:
      - spring-cloud-network
networks:
  spring-cloud-network:
      driver: bridge