server:
  port: 9000
spring:
  application:
    name: card-service
  profiles:
    active: prod
  datasource:
    url: jdbc:mysql://card-database:3306/card?useSSL=false&allowPublicKeyRetrieval=true
    username: "root"
    password: "0000"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
  flyway: # This is for the database migration
    enabled: true
    baseline-version: 1.0.0
    baseline-on-migrate: true
    validate-on-migrate: true
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    default-schema: card
  config:
    import: optional:configserver:http://config:8071
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoint: # This is for the /actuator/shutdown endpoint
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
  info: # This is for the /actuator/info endpoint
    env:
      enabled: true

endpoints: # Enable the /actuator/shutdown endpoint
  shutdown:
    enabled: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-server:8070/eureka/

info: # This is for the /actuator/info endpoint to be seen in eureka dashboard
  app:
    name: "card"
    description: "Card Service for Bank Application"
    version: "1.0.0"