server:
  port: 8072

spring:
  application:
    name: gateway-server
  config:
    import: optional:configserver:http://config:8071
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
  info: # This is for the /actuator/info endpoint
    env:
      enabled: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-server:8070/eureka

info: # This is for the /actuator/info endpoint to be seen in eureka dashboard
  app:
    name: "gateway server"
    description: "Gateway server for Bank Application"
    version: "1.0.0"