server:
  port: 8090
spring:
  application:
    name: loan-service
  profiles:
    active: prod
  datasource:
    url: jdbc:mysql://loan-database:3306/loan?useSSL=false&allowPublicKeyRetrieval=true
    username: "root"
    password: "0000"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
  flyway:
    enabled: true
    baseline-version: 1.0.0
    baseline-on-migrate: true
    validate-on-migrate: true
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    default-schema: loan
  config:
    import: optional:configserver:http://config:8071
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"