spring:
  application:
    name: "eureka"
  config:
    import: optional:configserver:http://config:8071

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  metrics: # This is for the /actuator/metrics endpoint to micrometer
    tags:
      application: ${spring.application.name}

server:
  port: 8070

eureka:
  instance:
    hostname: eureka-server
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/